<<<<<<< HEAD
name: 'dbt_intro_olist_real'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_intro_olist_real'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  dbt_intro_olist_real:
    # Config for all models in staging/
    staging:
      +materialized: view
      +tags: ["staging"]
    
    # Config for all models in marts/
    marts:
      +materialized: table
      +tags: ["marts"]

# Seeds configuration
seeds:
  dbt_intro_olist_real:
    +schema: seeds

vars:
  # Limit data in dev for faster iteration
  dev_limit: 1000
=======
name: 'dbt_intro_olist'
version: '1.0.0'
config-version: 2

profile: 'dbt_intro_olist'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
seed-paths: ["seeds"]

clean-targets:
  - "target"
  - "dbt_packages"
>>>>>>> 1d1be8c (Starter files with lab reference SQL files)
